################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
xcp \
wpan \
webcache \
trace \
tora \
tools \
tmix \
tcp \
tcp/linux \
tcp/linux/src \
src_rtg \
sensor-nets \
sctp \
satellite \
routing \
routealgo \
realaudio \
rap \
queue \
qs \
pushback \
puma \
plm \
pgm \
packmime \
olsr \
. \
nix \
mpls \
mobile \
mdart \
mcast \
mac \
linkstate \
link \
lib \
indep-utils/webtrace-conv/ucb \
indep-utils/webtrace-conv/nlanr \
indep-utils/webtrace-conv/epa \
indep-utils/webtrace-conv/dec \
indep-utils/propagation \
indep-utils/model-gen \
indep-utils/dosreduce \
indep-utils/dosdbell \
indep-utils/cmu-scen-gen/setdest \
imep \
gen \
gaf \
emulate \
empweb \
dsr \
dsdv \
doc/figures \
diffusion3/ns \
diffusion3/lib/nr \
diffusion3/lib/main \
diffusion3/lib \
diffusion3/filters/rmst \
diffusion3/filters/misc \
diffusion3/filters/gear \
diffusion3/filters/diffusion \
diffusion3/filter_core \
diffusion3/apps/rmst_examples \
diffusion3/apps/ping \
diffusion3/apps/gear_examples \
diffusion \
diffserv \
delaybox \
dccp \
common \
classifier \
baytcp \
asim \
apps \
aomdv \
aodv \
adc \

